package yousang.rest_server.domain.model

import yousang.rest_server.domain.exception.BadRequestException
import java.time.LocalDateTime

/**
 * 로또 6/45 티켓 도메인 모델
 *
 * 비즈니스 규칙:
 * - 1~45 범위의 숫자 중 정확히 6개를 선택
 * - 중복된 숫자는 허용되지 않음
 * - 번호는 자동 정렬됨
 */
data class LottoTicket(
    val id: Long? = null,
    val userId: Long,
    val drawNumber: Int, // 회차
    val numbers: List<Int>, // 선택한 6개의 번호 (정렬됨)
    val isAutoGenerated: Boolean, // 자동 생성 여부
    val purchaseDate: LocalDateTime = LocalDateTime.now(),
    val price: Int = 1000, // 로또 한 게임 가격 (1,000원)
    val isWinningChecked: Boolean = false,
    val winningRank: Int? = null, // 1등~5등, null이면 미당첨
    val winningAmount: Long? = null
) {
    init {
        validateNumbers(numbers)
    }

    companion object {
        const val MIN_NUMBER = 1
        const val MAX_NUMBER = 45
        const val REQUIRED_COUNT = 6
        const val TICKET_PRICE = 1000

        /**
         * 랜덤 로또 번호 생성
         */
        fun generateRandom(userId: Long, drawNumber: Int): LottoTicket {
            val randomNumbers = (MIN_NUMBER..MAX_NUMBER)
                .shuffled()
                .take(REQUIRED_COUNT)
                .sorted()

            return LottoTicket(
                userId = userId,
                drawNumber = drawNumber,
                numbers = randomNumbers,
                isAutoGenerated = true
            )
        }

        /**
         * 수동 로또 번호 생성
         */
        fun createManual(userId: Long, drawNumber: Int, numbers: List<Int>): LottoTicket {
            return LottoTicket(
                userId = userId,
                drawNumber = drawNumber,
                numbers = numbers.sorted(),
                isAutoGenerated = false
            )
        }

        private fun validateNumbers(numbers: List<Int>) {
            // 개수 확인
            if (numbers.size != REQUIRED_COUNT) {
                throw BadRequestException("로또 번호는 정확히 ${REQUIRED_COUNT}개여야 합니다. 현재: ${numbers.size}개")
            }

            // 중복 확인
            if (numbers.distinct().size != REQUIRED_COUNT) {
                throw BadRequestException("로또 번호에 중복이 있습니다: $numbers")
            }

            // 범위 확인
            numbers.forEach { number ->
                if (number !in MIN_NUMBER..MAX_NUMBER) {
                    throw BadRequestException("로또 번호는 $MIN_NUMBER~$MAX_NUMBER 범위여야 합니다. 잘못된 번호: $number")
                }
            }
        }
    }

    /**
     * 당첨 정보 업데이트
     */
    fun withWinningInfo(rank: Int?, amount: Long?): LottoTicket {
        return copy(
            isWinningChecked = true,
            winningRank = rank,
            winningAmount = amount
        )
    }

    /**
     * 당첨 여부 확인
     */
    fun isWinning(): Boolean = winningRank != null && winningRank!! <= 5

    /**
     * 정렬된 번호 반환 (하위 호환성)
     */
    fun sortedNumbers(): List<Int> = numbers.sorted()
}
