package yousang.rest_server.domain.model

import yousang.rest_server.domain.exception.BadRequestException
import java.time.LocalDateTime

/**
 * 연금복권 티켓 도메인 모델
 *
 * 비즈니스 규칙:
 * - 조: 1~5 중 선택
 * - 번호: 000000~999999 (6자리)
 * - 각 조는 독립적인 추첨
 */
data class PensionLotteryTicket(
    val id: Long? = null,
    val userId: Long,
    val drawNumber: Int, // 회차
    val group: Int, // 조 (1~5)
    val number: Int, // 6자리 번호 (000000~999999)
    val isAutoGenerated: Boolean, // 자동 생성 여부
    val purchaseDate: LocalDateTime = LocalDateTime.now(),
    val price: Int = 1000, // 연금복권 가격 (1,000원)
    val isWinningChecked: Boolean = false,
    val winningRank: Int? = null, // 1등~7등, null이면 미당첨
    val winningAmount: Long? = null,
    val monthlyPension: Long? = null // 1등의 경우 월 지급액
) {
    init {
        validateGroup(group)
        validateNumber(number)
    }

    companion object {
        const val MIN_GROUP = 1
        const val MAX_GROUP = 5
        const val MIN_NUMBER = 0
        const val MAX_NUMBER = 999999
        const val TICKET_PRICE = 1000

        /**
         * 랜덤 연금복권 번호 생성
         */
        fun generateRandom(userId: Long, drawNumber: Int): PensionLotteryTicket {
            val randomGroup = (MIN_GROUP..MAX_GROUP).random()
            val randomNumber = (MIN_NUMBER..MAX_NUMBER).random()

            return PensionLotteryTicket(
                userId = userId,
                drawNumber = drawNumber,
                group = randomGroup,
                number = randomNumber,
                isAutoGenerated = true
            )
        }

        /**
         * 수동 연금복권 번호 생성
         */
        fun createManual(userId: Long, drawNumber: Int, group: Int, number: Int): PensionLotteryTicket {
            return PensionLotteryTicket(
                userId = userId,
                drawNumber = drawNumber,
                group = group,
                number = number,
                isAutoGenerated = false
            )
        }

        private fun validateGroup(group: Int) {
            if (group !in MIN_GROUP..MAX_GROUP) {
                throw BadRequestException("연금복권 조는 $MIN_GROUP~$MAX_GROUP 범위여야 합니다. 잘못된 조: $group")
            }
        }

        private fun validateNumber(number: Int) {
            if (number !in MIN_NUMBER..MAX_NUMBER) {
                throw BadRequestException("연금복권 번호는 $MIN_NUMBER~$MAX_NUMBER 범위여야 합니다. 잘못된 번호: $number")
            }
        }
    }

    /**
     * 번호를 6자리 문자열로 포맷팅
     */
    fun getFormattedNumber(): String = number.toString().padStart(6, '0')

    /**
     * 전체 번호를 "조-번호" 형식으로 포맷팅
     * 예: "1조-123456"
     */
    fun getFullFormattedNumber(): String = "${group}조-${getFormattedNumber()}"

    /**
     * 당첨 정보 업데이트
     */
    fun withWinningInfo(rank: Int?, amount: Long?, monthlyPension: Long? = null): PensionLotteryTicket {
        return copy(
            isWinningChecked = true,
            winningRank = rank,
            winningAmount = amount,
            monthlyPension = monthlyPension
        )
    }

    /**
     * 당첨 여부 확인
     */
    fun isWinning(): Boolean = winningRank != null && winningRank!! <= 7
}
