package yousang.rest_server.adapter.`in`.web.dto

import yousang.rest_server.domain.model.LottoDrawResult
import yousang.rest_server.domain.model.LottoTicket
import yousang.rest_server.domain.model.PensionLotteryDrawResult
import yousang.rest_server.domain.model.PensionLotteryTicket
import java.time.LocalDateTime

/**
 * 로또 티켓 응답
 */
data class LottoTicketResponse(
    val id: Long?,
    val userId: Long,
    val drawNumber: Int,
    val numbers: List<Int>,
    val isAutoGenerated: Boolean,
    val purchaseDate: LocalDateTime,
    val price: Int,
    val isWinningChecked: Boolean,
    val winningRank: Int?,
    val winningAmount: Long?,
    val isWinning: Boolean
) {
    companion object {
        fun from(ticket: LottoTicket): LottoTicketResponse {
            return LottoTicketResponse(
                id = ticket.id,
                userId = ticket.userId,
                drawNumber = ticket.drawNumber,
                numbers = ticket.numbers,
                isAutoGenerated = ticket.isAutoGenerated,
                purchaseDate = ticket.purchaseDate,
                price = ticket.price,
                isWinningChecked = ticket.isWinningChecked,
                winningRank = ticket.winningRank,
                winningAmount = ticket.winningAmount,
                isWinning = ticket.isWinning()
            )
        }
    }
}

/**
 * 연금복권 티켓 응답
 */
data class PensionLotteryTicketResponse(
    val id: Long?,
    val userId: Long,
    val drawNumber: Int,
    val group: Int,
    val number: Int,
    val formattedNumber: String,
    val fullFormattedNumber: String,
    val isAutoGenerated: Boolean,
    val purchaseDate: LocalDateTime,
    val price: Int,
    val isWinningChecked: Boolean,
    val winningRank: Int?,
    val winningAmount: Long?,
    val monthlyPension: Long?,
    val isWinning: Boolean
) {
    companion object {
        fun from(ticket: PensionLotteryTicket): PensionLotteryTicketResponse {
            return PensionLotteryTicketResponse(
                id = ticket.id,
                userId = ticket.userId,
                drawNumber = ticket.drawNumber,
                group = ticket.group,
                number = ticket.number,
                formattedNumber = ticket.getFormattedNumber(),
                fullFormattedNumber = ticket.getFullFormattedNumber(),
                isAutoGenerated = ticket.isAutoGenerated,
                purchaseDate = ticket.purchaseDate,
                price = ticket.price,
                isWinningChecked = ticket.isWinningChecked,
                winningRank = ticket.winningRank,
                winningAmount = ticket.winningAmount,
                monthlyPension = ticket.monthlyPension,
                isWinning = ticket.isWinning()
            )
        }
    }
}

/**
 * 로또 추첨 결과 응답
 */
data class LottoDrawResultResponse(
    val id: Long?,
    val drawNumber: Int,
    val winningNumbers: List<Int>,
    val bonusNumber: Int,
    val drawDate: LocalDateTime,
    val firstPrizeAmount: Long,
    val firstPrizeWinnerCount: Int,
    val totalSalesAmount: Long
) {
    companion object {
        fun from(result: LottoDrawResult): LottoDrawResultResponse {
            return LottoDrawResultResponse(
                id = result.id,
                drawNumber = result.drawNumber,
                winningNumbers = result.winningNumbers,
                bonusNumber = result.bonusNumber,
                drawDate = result.drawDate,
                firstPrizeAmount = result.firstPrizeAmount,
                firstPrizeWinnerCount = result.firstPrizeWinnerCount,
                totalSalesAmount = result.totalSalesAmount
            )
        }
    }
}

/**
 * 연금복권 추첨 결과 응답
 */
data class PensionLotteryDrawResultResponse(
    val id: Long?,
    val drawNumber: Int,
    val winningGroup: Int,
    val winningNumber: Int,
    val formattedWinningNumber: String,
    val bonusNumbers: List<Int>,
    val drawDate: LocalDateTime,
    val firstPrizeWinnerCount: Int,
    val totalSalesAmount: Long
) {
    companion object {
        fun from(result: PensionLotteryDrawResult): PensionLotteryDrawResultResponse {
            return PensionLotteryDrawResultResponse(
                id = result.id,
                drawNumber = result.drawNumber,
                winningGroup = result.winningGroup,
                winningNumber = result.winningNumber,
                formattedWinningNumber = result.getFormattedWinningNumber(),
                bonusNumbers = result.bonusNumbers,
                drawDate = result.drawDate,
                firstPrizeWinnerCount = result.firstPrizeWinnerCount,
                totalSalesAmount = result.totalSalesAmount
            )
        }
    }
}

/**
 * 로또 티켓 목록 응답
 */
data class LottoTicketsResponse(
    val tickets: List<LottoTicketResponse>,
    val totalCount: Int,
    val totalAmount: Long
) {
    companion object {
        fun from(tickets: List<LottoTicket>): LottoTicketsResponse {
            return LottoTicketsResponse(
                tickets = tickets.map { LottoTicketResponse.from(it) },
                totalCount = tickets.size,
                totalAmount = tickets.sumOf { it.price.toLong() }
            )
        }
    }
}

/**
 * 연금복권 티켓 목록 응답
 */
data class PensionLotteryTicketsResponse(
    val tickets: List<PensionLotteryTicketResponse>,
    val totalCount: Int,
    val totalAmount: Long
) {
    companion object {
        fun from(tickets: List<PensionLotteryTicket>): PensionLotteryTicketsResponse {
            return PensionLotteryTicketsResponse(
                tickets = tickets.map { PensionLotteryTicketResponse.from(it) },
                totalCount = tickets.size,
                totalAmount = tickets.sumOf { it.price.toLong() }
            )
        }
    }
}
