package yousang.rest_server.domain.model

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import yousang.rest_server.domain.exception.BadRequestException
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * 로또 티켓 도메인 모델 테스트
 */
class LottoTicketTest {

    @Test
    fun `랜덤 로또 번호 생성 - 6개의 정렬된 고유 번호 생성`() {
        // given
        val userId = 1L
        val drawNumber = 1000

        // when
        val ticket = LottoTicket.generateRandom(userId, drawNumber)

        // then
        assertEquals(6, ticket.numbers.size)
        assertEquals(ticket.numbers.sorted(), ticket.numbers) // 정렬 확인
        assertEquals(6, ticket.numbers.distinct().size) // 중복 없음 확인
        assertTrue(ticket.isAutoGenerated)
        assertTrue(ticket.numbers.all { it in 1..45 })
    }

    @Test
    fun `수동 로또 번호 생성 - 유효한 번호로 티켓 생성`() {
        // given
        val userId = 1L
        val drawNumber = 1000
        val numbers = listOf(7, 14, 21, 28, 35, 42)

        // when
        val ticket = LottoTicket.createManual(userId, drawNumber, numbers)

        // then
        assertEquals(6, ticket.numbers.size)
        assertEquals(numbers.sorted(), ticket.numbers)
        assertFalse(ticket.isAutoGenerated)
    }

    @Test
    fun `잘못된 개수의 번호로 생성 시 예외 발생`() {
        // given
        val userId = 1L
        val drawNumber = 1000
        val invalidNumbers = listOf(1, 2, 3, 4, 5) // 5개만

        // when & then
        assertThrows<BadRequestException> {
            LottoTicket.createManual(userId, drawNumber, invalidNumbers)
        }
    }

    @Test
    fun `중복된 번호로 생성 시 예외 발생`() {
        // given
        val userId = 1L
        val drawNumber = 1000
        val duplicateNumbers = listOf(1, 2, 3, 4, 5, 5) // 5가 중복

        // when & then
        assertThrows<BadRequestException> {
            LottoTicket.createManual(userId, drawNumber, duplicateNumbers)
        }
    }

    @Test
    fun `범위 밖 번호로 생성 시 예외 발생`() {
        // given
        val userId = 1L
        val drawNumber = 1000
        val outOfRangeNumbers = listOf(0, 10, 20, 30, 40, 46) // 0과 46은 범위 밖

        // when & then
        assertThrows<BadRequestException> {
            LottoTicket.createManual(userId, drawNumber, outOfRangeNumbers)
        }
    }

    @Test
    fun `당첨 정보 업데이트 테스트`() {
        // given
        val ticket = LottoTicket.generateRandom(1L, 1000)
        val rank = 3
        val amount = 1_500_000L

        // when
        val updated = ticket.withWinningInfo(rank, amount)

        // then
        assertTrue(updated.isWinningChecked)
        assertEquals(rank, updated.winningRank)
        assertEquals(amount, updated.winningAmount)
        assertTrue(updated.isWinning())
    }

    @Test
    fun `미당첨 티켓은 isWinning이 false`() {
        // given
        val ticket = LottoTicket.generateRandom(1L, 1000)

        // when
        val updated = ticket.withWinningInfo(null, null)

        // then
        assertTrue(updated.isWinningChecked)
        assertFalse(updated.isWinning())
    }
}
