package yousang.rest_server.domain.model

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import yousang.rest_server.domain.exception.BadRequestException
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * 연금복권 티켓 도메인 모델 테스트
 */
class PensionLotteryTicketTest {

    @Test
    fun `랜덤 연금복권 번호 생성`() {
        // given
        val userId = 1L
        val drawNumber = 100

        // when
        val ticket = PensionLotteryTicket.generateRandom(userId, drawNumber)

        // then
        assertTrue(ticket.group in 1..5)
        assertTrue(ticket.number in 0..999999)
        assertTrue(ticket.isAutoGenerated)
    }

    @Test
    fun `수동 연금복권 번호 생성`() {
        // given
        val userId = 1L
        val drawNumber = 100
        val group = 3
        val number = 123456

        // when
        val ticket = PensionLotteryTicket.createManual(userId, drawNumber, group, number)

        // then
        assertEquals(group, ticket.group)
        assertEquals(number, ticket.number)
        assertFalse(ticket.isAutoGenerated)
    }

    @Test
    fun `잘못된 조 번호로 생성 시 예외 발생`() {
        // given
        val userId = 1L
        val drawNumber = 100
        val invalidGroup = 6 // 1~5 범위 밖

        // when & then
        assertThrows<BadRequestException> {
            PensionLotteryTicket.createManual(userId, drawNumber, invalidGroup, 123456)
        }
    }

    @Test
    fun `잘못된 번호로 생성 시 예외 발생`() {
        // given
        val userId = 1L
        val drawNumber = 100
        val invalidNumber = 1_000_000 // 범위 밖

        // when & then
        assertThrows<BadRequestException> {
            PensionLotteryTicket.createManual(userId, drawNumber, 1, invalidNumber)
        }
    }

    @Test
    fun `번호 포맷팅 테스트`() {
        // given
        val ticket = PensionLotteryTicket.createManual(1L, 100, 2, 123)

        // when
        val formatted = ticket.getFormattedNumber()
        val fullFormatted = ticket.getFullFormattedNumber()

        // then
        assertEquals("000123", formatted)
        assertEquals("2조-000123", fullFormatted)
    }

    @Test
    fun `당첨 정보 업데이트 테스트`() {
        // given
        val ticket = PensionLotteryTicket.generateRandom(1L, 100)
        val rank = 1
        val amount = 1_680_000_000L
        val monthlyPension = 7_000_000L

        // when
        val updated = ticket.withWinningInfo(rank, amount, monthlyPension)

        // then
        assertTrue(updated.isWinningChecked)
        assertEquals(rank, updated.winningRank)
        assertEquals(amount, updated.winningAmount)
        assertEquals(monthlyPension, updated.monthlyPension)
        assertTrue(updated.isWinning())
    }
}
