apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rest-server

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
- pdb.yaml
- networkpolicy.yaml

# Common Labels
commonLabels:
  app.kubernetes.io/name: rest-server
  app.kubernetes.io/part-of: rest-server-platform

# Common Annotations
commonAnnotations:
  managed-by: kustomize
